#!/bin/bash

# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

source_bash_files() {

    declare -r CURRENT_DIRECTORY="$(pwd)"

    declare -r -a FILES_TO_SOURCE=(
        "bash_aliases"
        "bash_autocomplete"
        "bash_exports"
        "bash_functions"
        "bash_options"
        "bash_prompt"
        "bash.local"  # For local settings that should
                      # not be under version control.
    )

    local file=""
    local i=""

    # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

    cd "$(dirname "$(readlink "${BASH_SOURCE[0]}")")" \
        && . "../os/utils.sh"

    # shellcheck disable=SC2034
    declare -r OS="$(get_os)"

    # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

    for i in ${!FILES_TO_SOURCE[*]}; do

        file="$HOME/.${FILES_TO_SOURCE[$i]}"

        [ -r "$file" ] \
            && . "$file"

    done

    # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

    cd "$CURRENT_DIRECTORY"

}

# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

source_bash_files

# "$-" *i* This shell is interactive ;; *	echo This shell is not interactive ;;

# source /usr/local/bin/virtualenvwrapper.sh

# Only load Liquid Prompt in interactive shells, not from a script or from scp
lpath="/Users/spdaly/Projects/dotfiles/src/liquidprompt/liquidprompt"
[[ $- = *i* ]] && source $lpath

# z beats cd most of the time. `brew install z`
zpath="$(brew --prefix)/etc/profile.d/z.sh"
[[ $- = *i* ]] && [[ -s $zpath ]] && source $zpath

PATH="$PATH:$HOME/projects/dotfiles/src/bin:$HOME/.yarn/bin"

export PATH

unset -f source_bash_files

# The next line updates PATH for the Google Cloud SDK.
if [ -f '/Users/spdaly/Projects/google-cloud-sdk/path.bash.inc' ]; then source '/Users/spdaly/Projects/google-cloud-sdk/path.bash.inc'; fi

# The next line enables shell command completion for gcloud.
if [ -f '/Users/spdaly/Projects/google-cloud-sdk/completion.bash.inc' ]; then source '/Users/spdaly/Projects/google-cloud-sdk/completion.bash.inc'; fi
